name: bash_build

env:
  workdir: /builder

on:
  push:

jobs:
  build-bash:
    runs-on: ubuntu-20.04
    container:
      image: carterjones/manjaro
      volumes:
        - /dev:/dev
      options: --ulimit nofile=1024:10240 --privileged
    timeout-minutes: 720 # timeout 12h
    steps:
      - name: Preserve evn set in the container
        run: |
          echo HOME=/builder >> "$GITHUB_ENV"
          echo PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin >> "$GITHUB_ENV"
      - name: Install build dependencies
        shell: bash
        working-directory: ${{ env.workdir }}
        run: |
          echo "Y"| sudo pacman -Sy base-devel git pacman sudo \
          bc docbook-xsl pahole inetutils \
          xmlto cpio make
      - name: Clone repos
        shell: bash
        working-directory: ${{ env.workdir }}
        run: |
          KERNEL=$(echo ${{ github.repository }} | cut -d'/' -f2)
          GITHUB_BRANCH=$(echo ${{ github.ref }}| cut -d'/' -f3)
          echo "KERNEL=${KERNEL}" >>$GITHUB_ENV
          sed -i "s/MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j8\"/g" /etc/makepkg.conf
          echo "PACKAGER=\"Yurii Huang <funningc0217@foxmail.com>\"" >> /etc/makepkg.conf
          cat /etc/makepkg.conf |grep "PACKAGER="
          su - builder -c "git clone https://github.com/${{ github.repository }}.git -b ${GITHUB_BRANCH} src"
          su - builder -c "cp -arpf src/pacman/* ./"
      - name: Build bash
        shell: bash
        working-directory: ${{ env.workdir }}
        run: |
          echo "whoami: $(whoami)"
          su - builder -c "makepkg PKGBUILD"
          ls -al; ls -al pkg
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ env.workdir }}/*.pkg.tar.zst
